version: '2'

services:

  app:
    image: docker-ruby-on-rails-dev:2.3.1 # change 2.3.1 to your ruby version
    ports:
      # puma
      - 9292:9292
      # rails server
      - 3000:3000
    volumes:
      # application source code:
      - ./webapp:/usr/src/app
      # bundle cache:
      - ./.bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development

  # comment out if you are planning to use database:
  # db:
  #   image: postgres:9.5.2
  #   volumes:
  #     - ./.db:/var/lib/postgresql
  #     - ./.db-init:/docker-entrypoint-initdb.d
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_DB: test_db
  #     POSTGRES_USER: test_user
  #     POSTGRES_PASSWORD: test_password
